apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber
  labels:
    app: kuber
spec:
  replicas: 5
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: gostatic
  template:
    metadata:
      labels:
        app: gostatic
    spec:
      containers:
      - name: kuber-gostatic
        image: vladbuk/gostatic:0.2
        ports:
        - containerPort: 8043
