apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-v1
  labels:
    app: kuber-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-server-v1
  template:
    metadata:
      labels:
        app: http-server-v1
    spec:
      containers:
      - name: kuber-k8sphp
        image: vladbuk/k8sphp:0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-service-v1
spec:
  selector:
    app: http-server-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

