apiVersion: v1
kind: ReplicationController
metadata:
  name: kuber-rc
spec:
  replicas: 3
  selector:
    app: nginx-server
  template:
    metadata:
      name: kuber-app
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx-server-image
        image: vladbuk/k8sphp:arm64
        ports:
        - containerPort: 80
